make update-repo-settings self-delete

diff --git a/script/update-repo-settings b/script/update-repo-settings
--- a/script/update-repo-settings
+++ b/script/update-repo-settings
@@ -1,7 +1,7 @@
 #!/bin/sh
 #/ script/update-repo-settings updates the settings for the GitHub repository to the preferred settings.
-#/ This should only need to be run once per repository, but can be run multiple times to override
-#/ any unwanted changes.
+#/ This should is only needed once per repository, so it deletes itself after running (actually it pushes
+#/ the change before updating the repository because the update disallows pushing changes to main).
 #/
 #/ This would normally be part of the one-time apply-template script, but it cannot be run
 #/ from GitHub Actions.
@@ -22,6 +22,16 @@ set -e
 
 CDPATH="" cd -- "$(dirname -- "$0")/.."
 
+# make sure nothing is staged
+if ! git diff --cached --quiet; then
+  echo "error: cannot run with staged changes" >&2
+  exit 1
+fi
+
+git rm --cached script/update-repo-settings
+git commit -q -m "Remove script/update-repo-settings"
+git push -q
+
 script/bindown -q install gh
 
 bin/gh repo edit \
@@ -41,3 +51,5 @@ bin/gh api '/repos/{owner}/{repo}/branches/main/protection' \
   -F 'required_status_checks[strict]=true' \
   -F 'required_status_checks[contexts][]=cibuild' \
   -F 'required_pull_request_reviews[required_approving_review_count]=0'
+
+rm script/update-repo-settings
